### PR TITLE
Revised CMAKE usage to reduce compile definition leakage to other target.

### PR DESCRIPTION
**Pull request by JeanPhilippeLebel**
Revised CMAKE usage to reduce compile definition leakage to other target.

### CODE REVIEW

**Comment by JeanPhilippeLebel** [comment]
those changes should not impact current users of the library unless they relied on public definitions what were exposed by the library.

**Comment by JeanPhilippeLebel** [comment]
After verification, the default CMAKE MSVC release flags already include /O2 and global optimization is disabled.

What led you to add those flags explicitly?

**Comment by TwinFan** [comment]
> After verification, the default CMAKE MSVC release flags already include /O2 and global optimization is disabled.
> 
> What led you to add those flags explicitly?

Well, I never verified what's included by default. Making things explicit has the advantage that I can rely on it and it is obvious what you get.

One comment above:

I don't quite understand where you incompatible command line options come from. I don't define `/RTC*` anywhere, so I assume you define that in your project. I do define `/O2`, but only for _Release_ builds. And for them I insist on optimization and would definitely not want Run Time Code checks in place. So...I don't get the issue, sorry.

So at the moment I don't quite see a need to change this optimization settings.

**Comment by JeanPhilippeLebel** [comment]
If you include XPMP2 using add_subdirectory, it can affect your main project and all other dependencies, as any flags set by XPMP2 could be modified or overridden by other libraries, and vice versa. Ideally, a library’s CMake file should not impact the consumers of that library.

This becomes challenging when managing a project with many dependencies.

One solution I considered is allowing XPMP2 to be built as a dynamic library. A flag (defaulting to off) could be provided to toggle this behavior, so existing users wouldn’t be affected.

I’m still evaluating the best way to implement this without breaking existing code. Currently, I have to manually modify the CMake file to integrate XPMP2 into my project. A simple example is the X-Plane SDK. The XPMP2 pulls the dependency (which is correct in this context) but my plugin also pulls it because I need to be able to build even if XPMP2 is disabled. I've created a FindXPlaneSDK.cmake file to be able to use find_package(XPlaneSDK), which is a nice step forward to make every library use the same SDK (assuming all libraries use the find_package call). 

Anyway, the dynamic library change has to be valuable to your users and not just me. 

For context, our plugin already offers most of the features of XPMP2, but we’re integrating it because one of our customers required the XPMP2 remote client capability. Since our plugin has a long history, adding a new library requires careful consideration.

**Pull request merged**
